name: task1
channels:
 - conda-forge
 - defaults
 - pytorch
dependencies:
 - baumwelch=0.3.1
 - ngram=1.3.9
 - numpy=1.18.1
 - openfst=1.7.6
 - pandas=0.25.1
 - pip=20.0.2
 - pynini=2.1.0
 - python=3.7.4
 - pytorch=1.2.0
 - pip:
   - fairseq==0.8.0
